# 服务器配置：端口 8080（默认，浏览器访问用）
server:
  port: 8080
# spring 数据库配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 连接本地mysql
  datasource:
    # 数据库 URL：quickmind_db 是你之前创建的数据库名（必须一致）
    url: jdbc:mysql://localhost:3306/quickmind_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root # 你的 MySQL 用户名（默认 root）
    password: 12345 # 你的 MySQL 密码（安装时设置的，必须填对）
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8.0 驱动（固定写法）
